# Generated by Django 3.2.5 on 2021-07-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Match Date')),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('match_round', models.IntegerField()),
                ('status', models.CharField(choices=[('BYE', 'BYE'), ('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=20)),
                ('player_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_2_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='left_previous',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='right_previous',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.RenameModel(
            old_name='TeamFixture',
            new_name='Fixture',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMatch',
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
        migrations.AddField(
            model_name='player',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team_fixture.fixture'),
        ),
        migrations.AddField(
            model_name='match',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches', to='team_fixture.fixture'),
        ),
        migrations.AddField(
            model_name='match',
            name='left_previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_next_match', to='team_fixture.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_matches', to='team_fixture.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_matches', to='team_fixture.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='right_previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_next_match', to='team_fixture.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_won', to='team_fixture.player'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('rank', 'fixture')},
        ),
    ]
