# Generated by Django 3.2.5 on 2021-07-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixture', '0002_auto_20210718_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
