# Generated by Django 3.2.5 on 2021-07-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixture', '0004_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'verbose_name': 'Team fixture', 'verbose_name_plural': 'Team Fixtures'},
        ),
    ]
