# Generated by Django 3.2.3 on 2021-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='icon',
            field=models.ImageField(upload_to='icons', verbose_name='image'),
        ),
    ]
